apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: mqtt-engelbrink-dev-host
  namespace: default
spec:
  hostname: mqtt.engelbrink.dev
---
apiVersion: getambassador.io/v2
kind:  TCPMapping
metadata:
  name:  mqtt-mapping
  namespace: default
spec:
  port: 1883
  service: vernemq-cluster:1883
---
apiVersion: getambassador.io/v2
kind:  TCPMapping
metadata:
  name:  mqtt-mapping-tls
  namespace: default
spec:
  port: 8883
  service: vernemq-cluster:8883
