apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: api-engelbrink-dev-host
  namespace: default
spec:
  hostname: api.engelbrink.dev
  acmeProvider:
    authority: 'https://acme-v02.api.letsencrypt.org/directory'
    email: hengel2810@gmail.com
  tlsSecret:
    name: api-engelbrink-dev-tls
  requestPolicy:
    insecure:
      action: Reject
---
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: api-engelbrink-dev-host-context
spec:
  hosts:
    - api.engelbrink.dev
  secret: api-engelbrink-dev-tls
  min_tls_version: v1.2
  cipher_suites:
    - "[TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384]"
    - "[TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256]"
    - "[TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]"
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  api-mapping
  namespace: default
spec:
  prefix: /
  host: api.engelbrink.dev
  service: oathkeeper-proxy:4455
  add_response_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  labels:
    ambassador:
      - request_label_group:
          - remote_address
---
apiVersion: getambassador.io/v2
kind: RateLimit
metadata:
  name: backend-rate-limit
spec:
  domain: ambassador
  limits:
    - pattern: [{remote_address: "*"}]
      rate: 5
      unit: minute
