apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: device-service
    namespace: default
  - kind: ServiceAccount
    name: cert-service
    namespace: default
  - kind: ServiceAccount
    name: vernemq-cluster
    namespace: default
