apiVersion: voyager.appscode.com/v1beta1
kind: Certificate
metadata:
  name: main-domain-cert
  namespace: default
spec:
  domains:
  - 'engelbrink.dev'
  - '*.engelbrink.dev'
  acmeUserSecretName: acme-account
  challengeProvider:
    dns:
      provider: digitalocean
      credentialSecretName: do-dns-secret
  storage:
    secret:
      name: cert-main-domain
