apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: basic-root-policy
  namespace: default
spec:
  privileged: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - '*'
